# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        ('djangocms_link', '0013_fix_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='file_link',
            field=filer.fields.file.FilerFileField(blank=True, help_text='If provided links a file from the filer app', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='File download',
        ),
    ]
