# Generated by Django 6.0.2 on 2026-03-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_link', '0019_alter_link_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='target',
            new_name='link_target',
        ),
    ]
